### ISSUE TITLE
Could you add a toggle loop when importing animations?

### ISSUE THREAD

**Issue by TubyUwU** [hectorid/aseprite_importer#8]
Could you add a toggle loop when importing animations? Or perhaps theres an option on Aseprite

**Comment by hectorid** [comment]
Hey @TubyUwU , the JSON data that is exported from Aseprite doesn't tell if the animation (tag) is to loop or not, because it always loop by default in the editor. When the plugin imports this data to Godot, it creates an Animation object that has a lot of properties that can be tweaked. And one of them is animation looping: 
![image](https://user-images.githubusercontent.com/17878308/113648930-de462600-9663-11eb-9054-340d850bc44a.png)
